---
#tasks file for ansible-adagios-agent-windows
- name: Check if NSClient++ is installed
  win_stat:
    path: 'C:\PROGRA~1\NSClient++\nscp.exe'
  register: is_nscp_installed

- debug:
    var: is_nscp_installed
  
- name: Check the current installed version of Adagios agent
  win_command: 'C:\PROGRA~1\NSClient++\nscp.exe settings --path /adagios --key "adagios_agent_version" --show'
  register: adagios_agent_version_output
  when: is_nscp_installed.stat.exists == True

- debug:
    var: adagios_agent_version

- debug:
    var: adagios_agent_version_output
    
- debug:
    var: adagios_agent_version_output.stdout

- set_fact: 
    adagios_agent_version_installed: "{{ adagios_agent_version_installed.stdout | default('0') }}"
  
- debug:
    var: adagios_agent_version_installed

- name: Download Adagios agent version {{ adagios_agent_version }} from Github
  win_get_url:
    url: https://github.com/opinkerfi/adagios-agent-windows/archive/{{ adagios_agent_version }}.zip
    dest: '{{ ansible_env.TEMP }}\{{ adagios_agent_version }}.zip'
    force: yes
    validate_certs: no
    timeout: 100
  when: adagios_agent_version_installed != adagios_agent_version

- name: Unzip
  win_unzip:
    src: '{{ ansible_env.TEMP }}\{{ adagios_agent_version }}.zip'
    dest: '{{ ansible_env.TEMP }}'
    delete_archive: yes
  when: adagios_agent_version_installed.stdout != adagios_agent_version

- name: Install Adagios agent (NSClient++ with OKconfig support for Adagios)
  win_command: '{{ ansible_env.TEMP }}\adagios-agent-windows-{{ adagios_agent_version }}\Deploy-Application.exe'
  when: adagios_agent_version_installed.stdout != adagios_agent_version

- name: Configure nscp allowed_hosts
  win_command: 'C:\PROGRA~1\NSClient++\nscp.exe settings --path /settings/default --key "allowed hosts" --set "{{ allowed_hosts }}"'
  notify: restart_nscp
