---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: WindowsServer2016
    box: jborean93/WindowsServer2016
    groups:
      - windows
provisioner:
  name: ansible
  inventory:
    host_vars:
      WindowsServer2016:
        ansible_become: false
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55985
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
    group_vars:
      linux:
        ansible_become: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
